p8105_hw1_zg2486
================
2024-09-13

# Problem 1

1.  The data in the dataset:

``` r
library(tidyverse)

data("penguins", package = "palmerpenguins") 
  summary(penguins)
```

    ##       species          island    bill_length_mm  bill_depth_mm  
    ##  Adelie   :152   Biscoe   :168   Min.   :32.10   Min.   :13.10  
    ##  Chinstrap: 68   Dream    :124   1st Qu.:39.23   1st Qu.:15.60  
    ##  Gentoo   :124   Torgersen: 52   Median :44.45   Median :17.30  
    ##                                  Mean   :43.92   Mean   :17.15  
    ##                                  3rd Qu.:48.50   3rd Qu.:18.70  
    ##                                  Max.   :59.60   Max.   :21.50  
    ##                                  NA's   :2       NA's   :2      
    ##  flipper_length_mm  body_mass_g       sex           year     
    ##  Min.   :172.0     Min.   :2700   female:165   Min.   :2007  
    ##  1st Qu.:190.0     1st Qu.:3550   male  :168   1st Qu.:2007  
    ##  Median :197.0     Median :4050   NA's  : 11   Median :2008  
    ##  Mean   :200.9     Mean   :4202                Mean   :2008  
    ##  3rd Qu.:213.0     3rd Qu.:4750                3rd Qu.:2009  
    ##  Max.   :231.0     Max.   :6300                Max.   :2009  
    ##  NA's   :2         NA's   :2

There are 3 species of penguins, 3 islands, 2 missing values for bill
length, bill depth, flipper length, and body mass, sex (165 female, 168
male, and 11 missing values), year (2007 - 2009).

2.  The size of the dataset:

``` r
nrow(penguins)
```

    ## [1] 344

``` r
ncol(penguins)
```

    ## [1] 8

There are 344 rows and 8 columns in this dataset.

3.  The mean flipper length:

``` r
mean(pull(penguins, flipper_length_mm), na.rm = TRUE)
```

    ## [1] 200.9152

The mean flipper length = 200.9152 mm.

4.  Make and save the scatterplot of flipper length vs bill length:

``` r
penguins_plot <- ggplot(penguins, aes(x = bill_length_mm, y = flipper_length_mm, colour = species))+ geom_point()
  
ggsave("penguins.png", plot = penguins_plot) 
```

    ## Saving 7 x 5 in image

    ## Warning: Removed 2 rows containing missing values or values outside the scale range
    ## (`geom_point()`).

# Problem 2

``` r
set.seed(100)
  hw1_df = tibble(
    norm_samp = rnorm(n = 10),
    vec_logical = norm_samp > 0,
    vec_char = c("A","B","C","D","E","F","G","H","I","J"),
    vec_factor = factor(c("IN","NJ","NY","IN","IN","NJ","NJ","NY","NY","NJ"))
  )

  hw1_df
```

    ## # A tibble: 10 × 4
    ##    norm_samp vec_logical vec_char vec_factor
    ##        <dbl> <lgl>       <chr>    <fct>     
    ##  1   -0.502  FALSE       A        IN        
    ##  2    0.132  TRUE        B        NJ        
    ##  3   -0.0789 FALSE       C        NY        
    ##  4    0.887  TRUE        D        IN        
    ##  5    0.117  TRUE        E        IN        
    ##  6    0.319  TRUE        F        NJ        
    ##  7   -0.582  FALSE       G        NJ        
    ##  8    0.715  TRUE        H        NY        
    ##  9   -0.825  FALSE       I        NY        
    ## 10   -0.360  FALSE       J        NJ

``` r
  mean(pull(hw1_df, norm_samp))
```

    ## [1] -0.01795716

``` r
  mean(pull(hw1_df, vec_logical))
```

    ## [1] 0.5

``` r
  mean(pull(hw1_df, vec_char))
```

    ## Warning in mean.default(pull(hw1_df, vec_char)): argument is not numeric or
    ## logical: returning NA

    ## [1] NA

``` r
  mean(pull(hw1_df, vec_factor))
```

    ## Warning in mean.default(pull(hw1_df, vec_factor)): argument is not numeric or
    ## logical: returning NA

    ## [1] NA

We can get the mean of norm_samp, which is -0.018, and the mean of
vec_logical, which is 0.5. We cannot get the mean of vec_char and
vec_factor.

``` r
as.numeric(pull(hw1_df,vec_logical))
as.numeric(pull(hw1_df,vec_char))
as.numeric(pull(hw1_df,vec_factor))
```

The logical vector will convert to 0 and 1, and this can help to explain
why we get the mean of 0.5 for this vector. Character vector was
converted to ‘NA’, which make sense that it can’t be used to calculate
the mean. The factor vector will be convert to 1, 2, 3, which just
represent the level of the vector, not mean the value of each level of
factor are 1, 2, 3, so that help to explain why we can’t get the mean of
this vector.
